---
- hosts: all
  tasks:
    - name: Send MCC-MNC commands
      debug:
        msg: "Processing MCC={{ item.mcc }}, MNC={{ item.mnc }}"
      with_items: "{{ lookup('file', mcc_mnc_file).splitlines() | map('extract_mcc_mnc') }}"

