name: Parse MCC-MNC and Check Disk Space

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: "Path to the input.txt file containing MCC-MNC and server details"
        required: true
      inventory_file:
        description: "Path to the Ansible inventory file"
        required: true

jobs:
  parse_and_execute:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Parse input.txt
      - name: Parse MCC-MNC and Servers
        id: parse_input
        run: |
          input_file="${{ github.event.inputs.input_file }}"
          mcc_mnc_file="parsed_mcc_mnc.txt"
          servers_file="parsed_servers.txt"

          # Extract MCC-MNC pairs
          awk '/MCC-MNC:/ {flag=1; next} /SERVERS:/ {flag=0} flag {gsub(/\t/, ""); print}' "$input_file" | \
          while read -r line; do
            if [[ "$line" =~ ([0-9]{3})-([0-9]{2}) ]]; then
              mcc="${BASH_REMATCH[1]}"
              mnc="${BASH_REMATCH[2]}"
              echo "mcc=$mcc,mnc=$mnc" >> "$mcc_mnc_file"
            fi
          done

          # Extract servers
          awk '/SERVERS:/ {flag=1; next} {if (flag) {gsub(/\t/, ""); print}}' "$input_file" > "$servers_file"

          echo "Parsed MCC-MNC pairs:"
          cat "$mcc_mnc_file"
          echo "Parsed Servers:"
          cat "$servers_file"

      # Step 3: Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Step 4: Execute Ansible Playbook
      - name: Execute Disk Space Check
        run: |
          ansible-playbook -i ${{ github.event.inputs.inventory_file }} ansible_scripts/check_disk_space.yml
