name: Parse MCC-MNC and Execute Commands

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: "Path to the input.txt file containing MCC-MNC and server details"
        required: true

jobs:
  parse_and_execute:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Parse input.txt for MCC-MNC and servers
      - name: Parse MCC-MNC and Servers
        id: parse_input
        run: |
          input_file="${{ github.event.inputs.input_file }}"
          mcc_mnc_file="parsed_mcc_mnc.txt"
          target_inventory="target_inventory.ini"

          # Extract MCC-MNC pairs
          awk '/MCC-MNC:/ {flag=1; next} /SERVERS:/ {flag=0} flag {gsub(/\t/, ""); print}' "$input_file" | \
          while read -r line; do
            if [[ "$line" =~ ([0-9]{3})-([0-9]{2}) ]]; then
              mcc="${BASH_REMATCH[1]}"
              mnc="${BASH_REMATCH[2]}"
              echo "mcc=$mcc,mnc=$mnc" >> "$mcc_mnc_file"
            fi
          done

          echo "Parsed MCC-MNC pairs:"
          cat "$mcc_mnc_file"
          
          # Debugging server extraction
          echo "Extracting servers from input.txt:"
          awk '/SERVERS:/ {flag=1; next} {if (flag) {gsub(/\t/, ""); print}}' "$input_file"

          # Debugging inventory filtering
          awk '/SERVERS:/ {flag=1; next} {if (flag) {gsub(/\t/, ""); print}}' "$input_file" | \
          while read -r server; do
            echo "Looking for server: $server in inventory.ini"
            grep "^$server " inventory.ini >> "$target_inventory" || echo "Server $server not found in inventory.ini"
          done

          echo "Filtered inventory file:"
          cat "$target_inventory"

      # Step 3: Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # Step 4: Execute Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i target_inventory.ini ansible_scripts/send_mcc_mnc_commands.yml

