name: Ansible Workflow with Parse Input

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: "Path to the input file"
        default: "input.txt"
        required: true

jobs:
  parse-and-execute:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Run parse_input.sh
    - name: Parse Input File
      id: parse_input
      run: |
        input_file="${{ github.event.inputs.input_file }}"
        chmod +x parse_input.sh
        ./parse_input.sh "$input_file"
        
        # Output for the next steps
        echo "mcc_mnc_file=$(pwd)/parsed_mcc_mnc.txt" >> $GITHUB_ENV
        echo "inbound_file=$(pwd)/parsed_inbound.txt" >> $GITHUB_ENV
        echo "target_inventory=$(pwd)/target_inventory.ini" >> $GITHUB_ENV

    # Step 3: Execute Ansible Playbook
    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i "$target_inventory" playbook.yml
      env:
        target_inventory: ${{ env.target_inventory }}

    # Step 4: Log Results
    - name: Display Parsing Results
      run: |
        echo "Parsed MCC-MNC pairs:"
        cat "$mcc_mnc_file"
        echo "Parsed Inbound pairs:"
        cat "$inbound_file"
        echo "Filtered Target Inventory:"
        cat "$target_inventory"
      env:
        mcc_mnc_file: ${{ env.mcc_mnc_file }}
        inbound_file: ${{ env.inbound_file }}
        target_inventory: ${{ env.target_inventory }}

